feat: leverage cache to prevent unnecessary pushing and building
docker-mailserver/docker-mailserver pull request #14
Opened 2021-01-16 18:50 UTC by radicand

Fixed #12

2021-01-16 19:55 UTC, aendeavor commented
The image did not survive for longer than the first job.

2021-01-16 20:17 UTC, radicand commented
It works in a simple test repo I created, but am preoccupied at the moment and will come back to look at whats different here in a bit.

2021-01-16 20:26 UTC, wernerfred commented
I've set up a similiar workflow to test it. Will update with my findings/thoughts tomorrow.

2021-01-16 21:56 UTC, radicand commented
I found the error in my test repo, and on fixing it, have the same findings as here - as a result, I'm unclear if we can actually cache the built *image*, though the layers definitely do cache. As a result, I'd suggest we tack on running the test suite to the job that builds the test image. This means test suite can leverage the just-built local image, and if it passes, when the final build/publish step runs, it will benefit from the already-cached amd64 layers and just build the remaining platforms. POC: https://github.com/radicand/test-docker-build-cache

If this sounds good, I'll update the PR to match this workflow logic.

2021-01-16 22:08 UTC, aendeavor commented
> If this sounds good, I'll update the PR to match this workflow logic.

SGTM

2021-01-16 22:50 UTC, radicand commented
I can't commit to this branch currently - it says it's protected. Can you take a look why that would be the case and unprotect it?

2021-01-16 23:07 UTC, aendeavor commented
> 
> 
> I can't commit to this branch currently - it says it's protected. Can you take a look why that would be the case and unprotect it?

I have no idea why. Branch protection rules should not get in our way. But I will remove it for now completely.

2021-01-17 00:07 UTC, radicand commented
Passes now, open for review

2021-01-17 08:59 UTC, aendeavor approved these changes
LGTM

If you like, you can name the testing step in `default_on_push.yml` "Run test suite" (to be consistent uppercase), but this only a very minor detail. I will label it as can be merged, but I'd wait for @wernerfred's review too :) Then, by all means, go ahead and merge it yourself :D

2021-01-17 10:49 UTC, wernerfred requested changes
Nice work!
Did you test the ```.github/workflows/default_on_push.yml``` somewhere (private?) too?
I think it should run as the changes are the same for the testing part like in the PR action and for the publishing part there are only naming changes.

What do you think regarding my comments?

2021-01-17 10:49 UTC, wernerfred commented on .github/workflows/default_on_push.yml
> +          NAME=mailserver-testing:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
In the ```test_merge_request.yml``` this line ist split in two separate lines. I would keep it the same style in both files so either put a newline here or make the other occurence a single-line too.
I vote for the two line option :)

2021-01-17 10:49 UTC, wernerfred commented on .github/workflows/test_merge_requests.yml
> +      imagetag: ${{ steps.prep.outputs.imagetag }}
Why is this needed? The output that is later set and used is called ```tags``` and not ```imagetag```. Am I missing something here? If it is not necessary then the same lines are obsolete in ```.github/workflows/default_on_push.yml``` too

2021-01-17 11:04 UTC, aendeavor commented on .github/workflows/default_on_push.yml
> +          NAME=mailserver-testing:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
I'm for the two lines option too, but keep in mind to use `>` instead of `|` then for the YAML.

2021-01-17 13:21 UTC, aendeavor commented on .github/workflows/test_merge_requests.yml
> +      imagetag: ${{ steps.prep.outputs.imagetag }}
I was wondering about this too.

2021-01-17 14:03 UTC, radicand commented on .github/workflows/default_on_push.yml
> +          NAME=mailserver-testing:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
I've made this change now

2021-01-17 14:04 UTC, radicand commented on .github/workflows/test_merge_requests.yml
> +      imagetag: ${{ steps.prep.outputs.imagetag }}
Thanks for this catch, I've removed the unnecessary prep step altogether for the test phase since it has a single tag

2021-01-17 14:05 UTC, radicand commented on .github/workflows/default_on_push.yml
> +          NAME=mailserver-testing:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
> Nice work!
> Did you test the `.github/workflows/default_on_push.yml` somewhere (private?) too?

In my test repo I had it test based on push; so yes :)

2021-01-17 14:07 UTC, radicand commented
> @radicand can we then delete the `mailserver/testing` repository?

Yes

2021-01-17 15:05 UTC, wernerfred approved these changes
LGTM

2021-01-17 16:41 UTC, merged