added label for non-stale PRs
docker-mailserver/docker-mailserver pull request #2301
Opened 2021-11-15 08:25 UTC by georglauterbach

# Description

Follow up on #2300. Sorry for the extra work.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-11-15 10:29 UTC, casperklein requested changes
I wasn't aware, that PRs are also considered by stale bot, as we have no explicit config for PRs.

The workflow file and title should be renamed, to reflect also PRs.
Also the close message, tags, etc.  should be streamlined. ATM for PRs the label `stale` is used instead of `meta/stale` like in issues.

2021-11-15 10:35 UTC, wernerfred requested changes
Maybe i am a bit late to the party as #2300 got already merged but i would highly prefer a solution like suggested (`bot/ignore` or variations like `stalebot/ignore`) over the now introduced `[issue|pr]/not-stale`.

Imho we should avoid making statements on the actual state of an issue or pr (what `not-stale` implies as we cannot guarantee it - its state could change in future or other PRs or might be totally different depending of the individual working on this - but only maintainers can edit the labels not the contributor) but rather highlight that certain automation does not apply here.

2021-11-15 10:35 UTC, wernerfred commented on .github/workflows/close_stale_issues.yml
> +          exempt-pr-labels: "pr/not-stale"
```suggestion
          exempt-pr-labels: "bot/ignore"
```

2021-11-15 10:38 UTC, georglauterbach commented
I will take care.

2021-11-15 15:02 UTC, georglauterbach commented on .github/workflows/close_stale_issues.yml
> +          exempt-pr-labels: "pr/not-stale"
👍🏼

2021-11-15 16:24 UTC, casperklein approved these changes
LGTM. The only thing to consider is maybe, to write out "pull requests" instead of PR.

2021-11-15 17:05 UTC, wernerfred approved these changes
Thanks

2021-11-15 20:00 UTC, georglauterbach commented
If "PR" turns out to be confusing in the future, I will change it :)

2021-11-15 20:00 UTC, merged

2021-11-15 21:44 UTC, polarathene commented
Might not matter much, especially since this got merged already, but `bot/ignore` implies any bot should ignore it rather than something like `stale-bot/ignore`.

2021-11-16 08:32 UTC, georglauterbach commented
As we only have one bot at the moment, all is well. If we implement a new bot, we can change this too.