[docs] faq.md: update naked/bare domain section
docker-mailserver/docker-mailserver pull request #2446
Opened 2022-03-01 09:50 UTC by sportshead

# Description

Added a note to remove `OVERRIDE_HOSTNAME` in the env file if adding `mydestination` doesn't work. See #1731

Fixes #1731 

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-01 10:51 UTC, georglauterbach commented
Thank you for your first contribution.

--

- [x] @polarathene I remember there were some discussions about this variable. I'm currently using it so set my hostnamen In Kubernetes. But the variable may not be perfect - is there a replacement planned or do we want to adjust the working, or domething completely different?

2022-03-01 13:54 UTC, polarathene submitted a review, later dismissed

2022-03-01 14:05 UTC, polarathene commented
> But the variable may not be perfect - is there a replacement planned or do we want to adjust the working, or domething completely different?

I'm unable to contribute until I restore my main PC into a working/bootable state. My replacement monitor arrived yesterday, waiting on a few more components that should arrive this week, then I should be able to attempt a restore/backup + fresh OS install. All my DMS related work is on that systems disks :sweat_smile: 

IIRC, I had notes on how to approach that and being able to run our entire test suite easily with several different configurations would help establish confidence in dropping/replacing the ENV. Without access to my notes, I can't really comment more about it :(

I only recall the use-cases for it with k8s and also host network. I will likely be prioritizing other tasks for DMS when I can contribute again, but if someone wants to look further into this topic that is welcomed :+1:

2022-03-01 16:12 UTC, georglauterbach approved these changes

2022-03-01 18:48 UTC, casperklein requested changes

2022-03-01 18:48 UTC, casperklein commented on docs/content/faq.md
> +Add the latter line to `docker-data/dms/config/postfix-main.cf`. If that doesn't work, make sure that `OVERRIDE_HOSTNAME` is blank in your `mailserver.env` file (see [#1731](https://github.com/docker
```suggestion
Add the latter line to `docker-data/dms/config/postfix-main.cf`. If that doesn't work, make sure that `OVERRIDE_HOSTNAME` is blank in your `mailserver.env` file (see [#1731](https://github.com/docker-mailserver/docker-mailserver/issues/1731#issuecomment-753968425)). Without these changes there will be warnings in the logs like:
```

2022-03-02 01:54 UTC, sportshead commented
Will force push to fix the commits

2022-03-02 02:24 UTC, casperklein approved these changes

2022-03-02 09:10 UTC, georglauterbach approved these changes

2022-03-02 17:09 UTC, casperklein approved these changes

2022-03-03 07:24 UTC, merged