fix: remove SA reload for KAM
docker-mailserver/docker-mailserver pull request #2456
Opened 2022-03-03 10:34 UTC by georglauterbach

# Description

Reading https://github.com/docker-mailserver/docker-mailserver/issues/2412#issuecomment-1041529047 I should have intervened when the SA reload line was added. The comments
says:

``` QUOTE
Note: SpamAssassin runs under Amavis  (so there isn't a "spamd" process)
/etc/spamassassin/sa-update-hooks.d/amavisd-new   takes care of reloading SpamAssassin after rules are updated
So, there is no point running "/etc/init.d/spamassassin reload", because it will fail   ("/etc/cron.daily/spamassassin" runs this command, but fails)
```

Fixes an error reported by cron that the update failed (which is expected...)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2022-03-03 11:37 UTC, casperklein approved these changes

2022-03-03 13:09 UTC, polarathene requested changes

2022-03-03 13:09 UTC, polarathene commented on target/scripts/startup/setup-stack.sh
>  sa-update --gpgkey 24C063D8 --channel kam.sa-channels.mcgrail.com && \
`&& \` still relevant?

```suggestion
sa-update --gpgkey 24C063D8 --channel kam.sa-channels.mcgrail.com
```

2022-03-03 14:26 UTC, casperklein approved these changes

2022-03-04 22:17 UTC, polarathene approved these changes

2022-03-04 22:38 UTC, merged

2022-03-06 07:08 UTC, ghnp5 commented
Ah... I was going to report this :)

```
/etc/cron.daily/aaa_spamassassin_KAM:
Update available for channel kam.sa-channels.mcgrail.com: 1646438287 -> 1646497491
http: (curl) GET http://sa-update-kam.snb.it/1646497491.tar.gz, success
http: (curl) GET http://sa-update-kam.snb.it/1646497491.tar.gz.sha512, success
Update was available, and was downloaded and installed successfully
run-parts: /etc/cron.daily/spamassassin_kam exited with return code 1
```

SpamAssassin runs under Amavis, so "reload" doesn't work.

`/etc/cron.daily/spamassassin` runs "reload", but the script itself doesn't seem to report as returning exit code 1.