Add `reject_unknown_client_hostname` to main.cf
docker-mailserver/docker-mailserver pull request #2691
Opened 2022-07-24 15:07 UTC by GoliathLabs

# Description
As discussed in the below mentioned issue this adds the `reject_unknown_client_hostname` option.

Reference: http://www.postfix.org/postconf.5.html#reject_unknown_reverse_client_hostname

Fixes #2650 

## Type of change

- [X] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [X] If necessary I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

2022-07-24 15:08 UTC, GoliathLabs commented
Not sure whether change in the docs is needed

2022-07-25 00:09 UTC, polarathene commented
[From the associated issue](https://github.com/docker-mailserver/docker-mailserver/issues/2650#issuecomment-1160004457):

> * Users could additionally configure known problematic clients to bypass the restriction via [`check_client_access`](http://www.postfix.org/postconf.5.html#check_client_access).

It could be worth documenting that, but until an issue is raised regarding it, I'm fine avoiding docs for now as I'd like to know if this change does cause problems for users.

---

This change is for the more strict version than `reject_unknown_reverse_client_hostname` which was approved.

With `reject_unknown_client_hostname`, the [HELO hostname](https://www.postfix.org/postconf.5.html#smtp_helo_name) must have a DNS A record that resolves to the IP matching the client, otherwise the client is rejected.

I suspect that can be a common misconfiguration by our users based on past issues. For those using `OVERRIDE_HOSTNAME` ENV, [our scripts do export this as `HOSTNAME` ENV](https://github.com/docker-mailserver/docker-mailserver/blob/8a0c71bd0cacb7a558689d94cf6d0a67e180b7d4/target/scripts/helpers/dns.sh#L23), but I'm not sure if services like Postfix detect that (_it seems [we configure for that explicitly for Postfix](https://github.com/docker-mailserver/docker-mailserver/blob/8a0c71bd0cacb7a558689d94cf6d0a67e180b7d4/target/scripts/startup/setup-stack.sh#L117)_).

I realize this is about filtering out inbound mail, nothing related to outbound mail, but I was thinking of scenarios with tests or when one DMS instance sends to another.

---

Ideally any legitimate mail server is going to be configured correctly, and pass those additional conditions, so hopefully when users update, they're not going to find legitimate mail being rejected that is received from third-parties.

2022-07-25 00:14 UTC, polarathene approved these changes

2022-07-26 18:04 UTC, georglauterbach commented
I also think this is a worthwhile addition and a right one :)

2022-07-26 18:04 UTC, georglauterbach approved these changes

2022-07-27 12:30 UTC, GoliathLabs commented
@georglauterbach @polarathene one thing that I noticed yesterday that sending mails from another container on the same host will eventually fail: https://github.com/dani-garcia/vaultwarden/discussions/2647

2022-07-27 12:38 UTC, GoliathLabs commented
Normally you would want to have a separate host for your mails, but in some cases that is not the case. So we need to solve this somehow by allowing mails from the internal Docker networks. I tried both `connected-networks` and `network` as allowed networks, but in both cases the test mail is rejected because of the message `4.7.25 Client host rejected: cannot find your hostname`.

2022-07-27 15:09 UTC, polarathene commented
I figured you might get something like that happening :sweat_smile: 

You can play around with a fully offline setup with local DNS as [I demonstrate here](https://github.com/docker-mailserver/docker-mailserver/issues/2601#issuecomment-1135520225).

You change shouldn't cause new rejections if the client passes either permits: `permit_sasl_authenticated, permit_mynetworks`. Is your client sending on port 25 instead of 587/465? If so you'd need to sort out the network, which you can debug in [this method](https://github.com/docker-mailserver/docker-mailserver/blob/73ef30e14cb1b69679135f22b82f0511f3129ac5/target/scripts/startup/setup-stack.sh#L644) to ensure both containers have the same network/interface to connect to each other and that the IP falls within the subnet.

2022-07-28 13:29 UTC, casperklein requested changes
LGTM, however this should be fixed:

https://github.com/docker-mailserver/docker-mailserver/pull/2691#issuecomment-1196674618

2022-07-29 22:01 UTC, GoliathLabs commented
I am sending via STARTTLS on port 587. Both containers are each in their separate docker-compose files. I don't think the problem would persist if I'd put both containers in one docker-compose file, since vaultwarden is sending from subnet 172.21.0.0/16, while mailserver is on 172.21.0.0/16, so they don't share the same subnet. Also when creating and mounting a separate docker network nothing changes, because vaultwarden still sends mails over the default network instead of the new docker network I've created.

2022-07-29 22:10 UTC, GoliathLabs commented
I am sending over 587 and STARTTLS. When I change the permit_network to connected-networks or network, it still doesn't work. Interestingly, 172.25.0.1 is the gateway IP of the mailserver_default network, which normally shouldn't be a problem since we included it with either network or connected-works. Nevertheless, it doesn't seem to work.

The main.cf with connected-networks:

```
# Basic configuration
# myhostname =
alias_maps = hash:/etc/aliases
alias_database = hash:/etc/aliases
mydestination = $myhostname, localhost.$mydomain, localhost
relayhost =
mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 127.0.0.0/8 172.26.0.0/16 172.25.0.0/16
mailbox_size_limit = 0
recipient_delimiter = +
inet_interfaces = all
inet_protocols = all

```

2022-07-30 01:08 UTC, polarathene commented
Have you tried [following my advice for a local multi-instance setup](https://github.com/docker-mailserver/docker-mailserver/pull/2691#issuecomment-1196886177) with the local DNS config it shows?

It may still fail though as the Corefile there doesn't configure rDNS :thinking: 

---

I am unable to help investigate any time soon, but I did link to full offline setup you can adapt. I know it's not quite enough to copy/paste and test, but at least would provide a more common config to reproduce from, since you haven't really shared much information of your own for reproduction.

If the hostname is really an issue look in `/etc/hosts` for each container, and also try use DNS utilities to contact the other container by hostname (_within the containers themselves, not the docker host_) advertised from the SMTP HELO. Best to first try reproduce that error outside of all the mail software involved.

2022-08-03 20:58 UTC, GoliathLabs commented
My setup:
docker-compose.yml
```
version: '3.8'

services:
  mailserver:
    image: mailserver/docker-mailserver:11.1.0
    hostname: mail
    domainname: example.com
    env_file: mailserver.env
    depends_on:
      - ipv6nat
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # More information about the mailserver ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
#    dns:
#      - 5.1.66.255
#      - 185.150.99.255
#      - "2001:678:e68:f000::"
#      - "2001:678:ed0:f000::"
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./data:/var/mail/
      - ./state:/var/mail-state/
      - ./logs:/var/log/mail/
      - /etc/localtime:/etc/localtime:ro
      - ./config/:/tmp/docker-mailserver/
      - ./certs/:/certs
      - ./config/dovecot/20-lmtp.conf:/etc/dovecot/conf.d/20-lmtp.conf
      - ./config/dovecot/20-imap.conf:/etc/dovecot/conf.d/20-imap.conf
      - ./config/dovecot/20-pop3.conf:/etc/dovecot/conf.d/20-pop3.conf
      - ./config/dovecot/fts-xapian-plugin.conf:/etc/dovecot/conf.d/10-plugin.conf:ro
      - ./header_checks.pcre:/etc/postfix/maps/header_checks.pcre
      - /opt/containers/traefik/data/acme.json:/etc/letsencrypt/acme.json:ro
      - ./cron/sa-learn:/etc/cron.d/sa-learn
      - ./cron/fts-index:/etc/cron.d/fts-index
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    networks:
      - default
      - mail

  ipv6nat:
    restart: always
    image: robbertkl/ipv6nat:0.4.4
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
    network_mode: "host"

  autodiscover:
    image: monogramm/autodiscover-email-settings:production
    container_name: autodiscover
    environment:
      - COMPANY_NAME=Morph Network
      - SUPPORT_URL=https://autodiscover.example.com
      - DOMAIN=example.com
      # IMAP configuration (host mandatory to enable)
      - IMAP_HOST=IMAP.example.com
      - IMAP_PORT=143
      - IMAP_SOCKET=STARTTLS
      # SMTP configuration (host mandatory to enable)
      - SMTP_HOST=SMTP.example.com
      - SMTP_PORT=587
      - SMTP_SOCKET=STARTTLS
      # Apple mobile config identifiers (identifier mandatory to enable)
      - PROFILE_IDENTIFIER=com.example.autodiscover
      - PROFILE_UUID=64263270-c3c3-43f7-9a81-65b75184c832
      - MAIL_UUID=1ec26cc6-7dc4-48bd-a2ef-d2a92e135202
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.autodiscover.entrypoints=http"
      - "traefik.http.routers.autodiscover.rule=Host(`autoconfig.example.com`, `autodiscover.example.com`)"
      - "traefik.http.middlewares.autodiscover-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.autodiscover.middlewares=autodiscover-https-redirect"
      - "traefik.http.routers.autodiscover-secure.entrypoints=https"
      - "traefik.http.routers.autodiscover-secure.rule=Host(`autoconfig.example.com`, `autodiscover.example.com`)"
      - "traefik.http.routers.autodiscover-secure.tls=true"
      - "traefik.http.routers.autodiscover-secure.tls.certresolver=http"
      - "traefik.http.routers.autodiscover-secure.service=autodiscover"
      - "traefik.http.services.autodiscover.loadbalancer.server.port=8000"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.autodiscover-secure.middlewares=secHeaders@file"
      - "traefik.port=8000"
    networks:
      - proxy

  roundcubemail:
    image: roundcube/roundcubemail:1.5.x-fpm-alpine
    container_name: roundcubemail
    # restart: unless-stopped
    depends_on:
      - roundcubedb
    links:
      - roundcubedb
    volumes:
      - /opt/containers/mailserver/roundcube:/var/www/html
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=roundcubedb # same as pgsql container name
      - ROUNDCUBEMAIL_DB_NAME=roundcube # same as pgsql POSTGRES_DB env name
      - ROUNDCUBEMAIL_DB_USER=roundcube # same as pgsql POSTGRES_USER env name
      - ROUNDCUBEMAIL_DB_PASSWORD=somefancypassword # same as pgsql POSTGRES_PASSWORD env name
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail.example.com
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail.example.com

  roundcubedb:
    image: postgres:14.4-alpine
    container_name: roundcubedb
    restart: unless-stopped
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=roundcube
      - POSTGRES_USER=roundcube
      - POSTGRES_PASSWORD=somefancypassword

  roundcubenginx:
    image: nginx:1.23.1-alpine
    container_name: roundcubenginx
    # restart: unless-stopped
      # If you need SSL connection
      # - '443:443'
    depends_on:
      - roundcubemail
    links:
      - roundcubemail
    volumes:
      - ./roundcube:/var/www/html
      - ./nginx/templates:/etc/nginx/templates
      # Provide a custom nginx conf
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # If you need SSL connection, you can provide your own certificates
      # - ./certs:/etc/letsencrypt
      # - ./certs-data:/data/letsencrypt
    environment:
      - NGINX_HOST=localhost # set your local domain or your live domain
      - NGINX_PHP_CGI=roundcubemail:9000 # same as roundcubemail container name
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.roundcube.entrypoints=http"
      - "traefik.http.routers.roundcube.rule=Host(`mail.example.com`, `webmail.example.com`, `imap.example.com`, `smtp.example.com`)"
      - "traefik.http.middlewares.roundcube-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.roundcube.middlewares=roundcube-https-redirect"
      - "traefik.http.routers.roundcube-secure.entrypoints=https"
      - "traefik.http.routers.roundcube-secure.rule=Host(`mail.example.com`, `webmail.example.com`, `imap.example.com`, `smtp.example.com`)"
      - "traefik.http.routers.roundcube-secure.tls=true"
      - "traefik.http.routers.roundcube-secure.tls.certresolver=http"
      - "traefik.http.routers.roundcube-secure.service=roundcube"
      - "traefik.http.services.roundcube.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.roundcube-secure.middlewares=secHeaders@file"
    networks:
      - default
      - proxy

  mta-sts:
    image: nginx:1.23.1-alpine
    restart: unless-stopped
    volumes:
      - /opt/containers/mailserver/mta-sts:/usr/share/nginx/html:ro
      - /opt/containers/mailserver/mta-sts.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mta-sts.entrypoints=http"
      - "traefik.http.routers.mta-sts.rule=Host(`mta-sts.example.com`)"
      - "traefik.http.middlewares.mta-sts-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.mta-sts.middlewares=mta-sts-https-redirect"
      - "traefik.http.routers.mta-sts-secure.entrypoints=https"
      - "traefik.http.routers.mta-sts-secure.rule=Host(`mta-sts.example.com)"
      - "traefik.http.routers.mta-sts-secure.tls=true"
      - "traefik.http.routers.mta-sts-secure.tls.certresolver=http"
      - "traefik.http.routers.mta-sts-secure.service=mta-sts"
      - "traefik.http.services.mta-sts.loadbalancer.server.port=80"
      - "traefik.docker.network=proxy"
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "wget -O /dev/null http://localhost || exit 1"]
      interval: 2s
      timeout: 30s
      retries: 15

networks:
  proxy:
    external: true
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0123:4567::/48
          gateway: fd00:0123:4567::1
  proxy:
    external [...]

2022-08-03 22:53 UTC, polarathene commented
`ipv6nat` is using `host` network mode (_I suspected a network was using this mode_). This prevents generating it's own `/etc/hosts` internally and instead mounts the host systems `/etc/hosts` instead. It may be contributing to the issue?

Your DMS container is only aware of the `default` and `mail` network, so only those should show up containers in `/etc/hosts` I think (_I can't quite recall the rules for how the container generates that_). But it also looks like `default` is your `ipv6nat` host mode network?

2022-08-04 19:40 UTC, GoliathLabs commented
@polarathene But `ipv6nat` is only used when IPv6 addresses are involved. Why would it's `/etc/hosts` file have anything to do with the mail server container and its it's DNS? Why do you think that the default network be the ipv6nat host network? Aren't they two different things (e.g. the default network is created when we start the docker-compose deployment with its separate address space)?

Any recommendations for modifying my docker-compose file?

Thanks in advance 😄

2022-08-04 22:38 UTC, casperklein commented
I just gave it a try and added `reject_unknown_client_hostname` to my configuration. I was able to send mails from another container that is on another docker network. Relevant logs:

<details>
<summary>Details</summary>

```
Aug  5 00:30:48 mail postfix/postscreen[26516]: CONNECT from [192.168.80.1]:39076 to [192.168.80.2]:25
Aug  5 00:30:48 mail postfix/postscreen[26516]: WHITELISTED [192.168.80.1]:39076
Aug  5 00:30:48 mail postfix/smtpd[26517]: connect from unknown[192.168.80.1]
Aug  5 00:30:48 mail opendmarc[2561]: ignoring connection from [192.168.80.1]
Aug  5 00:30:48 mail postfix/smtpd[26517]: D51F628030F5: client=unknown[192.168.80.1]
Aug  5 00:30:48 mail postfix/cleanup[26521]: D51F628030F5: message-id=<1659652248.769693.24423.nullmailer@smokeping>
Aug  5 00:30:48 mail opendkim[2555]: D51F628030F5: no signing table match for 'root@example.com'
Aug  5 00:30:48 mail opendkim[2555]: D51F628030F5: no signature data
Aug  5 00:30:48 mail postfix/qmgr[3806]: D51F628030F5: from=<root@example.com>, size=615, nrcpt=1 (queue active)
Aug  5 00:30:48 mail postfix/smtpd[26517]: disconnect from unknown[192.168.80.1] helo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Aug  5 00:30:50 mail postfix/smtpd-amavis/smtpd[26525]: connect from localhost[127.0.0.1]
Aug  5 00:30:50 mail postfix/smtpd-amavis/smtpd[26525]: 39CB828030F6: client=localhost[127.0.0.1]
Aug  5 00:30:50 mail postfix/cleanup[26521]: 39CB828030F6: message-id=<1659652248.769693.24423.nullmailer@smokeping>
Aug  5 00:30:50 mail postfix/qmgr[3806]: 39CB828030F6: from=<root@example.com>, size=789, nrcpt=1 (queue active)
Aug  5 00:30:50 mail postfix/smtpd-amavis/smtpd[26525]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Aug  5 00:30:50 mail amavis[3913]: (03913-04) Passed CLEAN {RelayedInbound}, [192.168.80.1]:39076 <root@example.com> -> <postmaster@example-destination.com>, Queue-ID: D51F628030F5, Message-ID: <1659652248.769693.24423.nullmailer@smokeping>, mail_id: lxosNWmEQxqN, Hits: -2.9, size: 581, queued_as: 39CB828030F6, 1360 ms
Aug  5 00:30:50 mail postfix/smtp-amavis/smtp[26522]: D51F628030F5: to=<postmaster@example-destination.com>, orig_to=<debug@example-destination.com>, relay=127.0.0.1[127.0.0.1]:10024], delay=1.4, delays=0.05/0.01/0/1.4, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 39CB828030F6)
Aug  5 00:30:50 mail postfix/qmgr[3806]: D51F628030F5: removed
Aug  5 00:30:50 mail dovecot: lmtp(26527): Connect from local
Aug  5 00:30:50 mail dovecot: lmtp(postmaster@example-destination.com)<26527><2UMGEppI7GKfZwAAdOYLmw>: msgid=<1659652248.769693.24423.nullmailer@smokeping>: saved mail to INBOX
Aug  5 00:30:50 mail postfix/lmtp[26526]: 39CB828030F6: to=<postmaster@example-destination.com>, relay=mail.example-destination.com[/var/run/dovecot/lmtp], delay=0.28, delays=0.05/0.01/0.01/0.22, dsn=2.0.0, status=sent (250 2.0.0 <postmaster@example-destination.com> 2UMGEppI7GKfZwAAdOYLmw Saved)
Aug  5 00:30:50 mail dovecot: lmtp(26527): Disconnect from local: Logged out (state=READY)
Aug  5 00:30:50 mail postfix/qmgr[3806]: 39CB828030F6: removed
```

</details>

**`main.cf:`**
```
mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 192.168.0.0/16
smtpd_sender_restrictions = reject_authenticated_sender_login_mismatch, permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain, reject_unknown_client_hostname
```

2022-08-04 23:36 UTC, polarathene commented
> Why would it's `/etc/hosts` file have anything to do with the mail server container and its it's DNS?

`/etc/hosts` gets populated by connected Docker networks and containers DNS if I recall correctly. Except when using network host mode, this instead copies `/etc/hosts` from the host system into the container.

> Why do you think that the default network be the ipv6nat host network? Aren't they two different things (e.g. the default network is created when we start the docker-compose deployment with its separate address space)?

I could be wrong, it's been a while since I've messed around with Docker networks. You're probably right about `ipv6nat` container just using the host mode network as separate from the `default` network.

You've got a lot more going on in your setup, I would simplify it down to bare minimal for using DMS. Create a separate `docker-compose.yml` using DMS with your change here, that doesn't involve RoundCube, IPv6 and the like. If like @casperklein you no longer have issues, then slowly introduce more of your real config and containers to try find out when it breaks.

---

> Yet I have to add my docker networks IP to the /etc/hosts file to finally be able to send via an internal IP

What was the before state of `/etc/hosts`?

This doesn't seem right..

```
172.31.0.3      mail.example.com mail
fd00:123:4567::3        mail.example.com mail
172.26.0.3      mail.example.com mail
172.31.0.1 mail.example.com mail
```

Doesn't that say `mail.example.com` should resolve to all those IP? That is not true though, this would be a hacky workaround.

The containers should be authorized to bypass the restriction instead.

---

> `mynetworks = 127.0.0.0/8 [::1]/128 [fe80::]/64 127.0.0.0/8 172.26.0.0/16 172.25.0.0/16`

Here only `172.26.x.x` is permitted, you have `172.31.x.x` subnet too (_was this originally `172.25.x.x`?_), and the IPv6 (_which container is that?_).

Note that you only want to permit IPs from your containers that should be allowed to send mail without auth, I assume `ipv6nat` is one you would want to specifically restrict such access to avoid an OpenRelay.

Likewise, be careful of proxies that don't carry over the original client info like IP/host, you don't want your container working around a restriction (_although I don't think it matters with this rule, which checks client hostname based on mail headers?_). There was one user who had an issue with RoundCube getting banned by Fail2Ban because all users were seen as from the same IP (the RoundCube container) when authenticating I think.

Ideally your containers would use SASL auth (587 or 465 port with user + password), not port 25 without auth. If that's acceptable, then `mynetworks` does not need to list those subnets.

2022-08-26 09:06 UTC, GoliathLabs commented
I'll try to do the debugging today

2022-08-26 11:13 UTC, casperklein commented
Update from my setup: Lots of rejected SPAM Mails with 0 false positives so far 👍

2022-08-29 19:32 UTC, GoliathLabs commented
I think I got it. My temporary `user-patches.sh` script put `reject_unkown_client_hostname` in the first position in the smtpd_sender_restrictions, which made the internal IPs of the other container fail because of the missing DNS entry, since the reject was put in the `main.cf` before the permit.

```
smtpd_sender_restrictions = reject_unknown_client_hostname, reject_unknown_reverse_client_hostname, reject_authenticated_sender_login_mismatch, permit_sasl_authenticated, permit_mynetworks, reject_unknown_sender_domain
disable_vrfy_command = yes
```

2022-08-29 22:08 UTC, casperklein approved these changes

2022-08-30 00:56 UTC, polarathene approved these changes

2022-08-30 01:00 UTC, polarathene commented
Don't merge until after 11.2 release? Just adding this comment for maintainers like myself that see approvals and forget to check the milestone target :sweat_smile: 

---

I'm a bit behind due to other commitments, but will try get the Dovecot encryption PR for 11.2 up before Sunday (_or at least the current state of it after rebasing_). If I do get too busy, feel free to delay the Dovecot Encryption feature to a future release instead.

2022-08-30 09:43 UTC, casperklein commented
IMO this can be in version `11.2`: As written, I had zero false positives with that setting. So in my experience it's a valuable anti-spam improvement that should be better included earlier than later.

@docker-mailserver/maintainers What's your oppinion and did you test it?

2022-08-30 12:35 UTC, georglauterbach commented
> @docker-mailserver/maintainers What's your oppinion and did you test it?

I agree, this can go into `v11.2.0`. Can someone please take care of relasing `v11.2.0` - I will be a short on time with my current PRs.. I can do it, but that may take a bit.

PS: Please set the correct milestone when merging :)

2022-09-05 10:18 UTC, georglauterbach commented
@polarathene if you agree that merging this is fine, please go ahead and do so - I have adjusted the milestone already :)

2022-09-05 20:56 UTC, polarathene commented
I'll merge.

My current commitments are delaying time to spare for this project, so the feature PR I've been working on and holding up the next release with may arrive later this month.

If you'd like to release 11.2 before then, I'm ok with that. I'll prepare a release sometime this week as time permits :+1:

2022-09-05 20:58 UTC, merged

2022-09-05 21:01 UTC, polarathene commented
Thanks @GoliathLabs for taking the time to look into this and contribute a PR! :heart:

2022-10-14 16:10 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
hello there,

first off, thanks for this wonderful project.

after upgrading from v11.1.0 to v11.2.0 I have found myself unable to receive from google (which I previously have been able to), as represented by the following (irrelevant parts redacted):
```logs
Oct 13 18:20:57 host docker-compose[20080]: mailserver-mailserver-1  | Oct 13 18:20:57 mail postfix/smtpd[51726]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x130.google.com>
Oct 13 19:30:11 host docker-compose[20080]: mailserver-mailserver-1  | Oct 13 19:30:11 mail postfix/smtpd[64354]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x636.google.com>
Oct 13 21:12:56 host docker-compose[20080]: mailserver-mailserver-1  | Oct 13 21:12:56 mail postfix/smtpd[83201]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x630.google.com>
Oct 13 22:31:38 host docker-compose[20080]: mailserver-mailserver-1  | Oct 13 22:31:38 mail postfix/smtpd[97655]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x134.google.com>
Oct 13 23:57:05 host docker-compose[20080]: mailserver-mailserver-1  | Oct 13 23:57:05 mail postfix/smtpd[113362]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ed1-x529.google.com>
Oct 14 02:25:33 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 02:25:33 mail postfix/smtpd[140705]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x634.google.com>
Oct 14 04:57:48 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 04:57:48 mail postfix/smtpd[168707]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x12f.google.com>
Oct 14 07:17:19 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 07:17:19 mail postfix/smtpd[194632]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x134.google.com>
Oct 14 07:20:12 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 07:20:12 mail postfix/smtpd[195162]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lj1-x22e.google.com>
Oct 14 07:26:57 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 07:26:57 mail postfix/smtpd[196407]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lj1-x233.google.com>
Oct 14 07:47:51 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 07:47:51 mail postfix/smtpd[200275]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x136.google.com>
Oct 14 08:29:05 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 08:29:05 mail postfix/smtpd[207832]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x12b.google.com>
Oct 14 09:19:24 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 09:19:24 mail postfix/smtpd[217091]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x629.google.com>
Oct 14 10:26:33 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 10:26:33 mail postfix/smtpd[229428]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x634.google.com>
Oct 14 10:30:34 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 10:30:34 mail postfix/smtpd[230166]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-wr1-x42d.google.com>
Oct 14 11:28:54 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 11:28:54 mail postfix/smtpd[240837]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ed1-x52d.google.com>
Oct 14 13:16:55 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 13:16:55 mail postfix/smtpd[260676]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x131.google.com>
Oct 14 13:36:08 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 13:36:08 mail postfix/smtpd[264297]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-wr1-x434.google.com>
Oct 14 14:34:30 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 14:34:30 mail postfix/smtpd[275053]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x62a.google.com>
Oct 14 16:10:13 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 16:10:13 mail postfix/smtpd[292589]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lf1-x136.google.com>
Oct 14 16:53:46 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 16:53:46 mail postfix/smtpd[300552]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-lj1-x233.google.com>
Oct 14 17:56:03 host docker-compose[20080]: mailserver-mailserver-1  | Oct 14 17:56:03 mail postfix/smtpd[312053]: NOQUEUE: reject: RCPT from unknown[192.168.224.1]: 450 4.7.25 Client host rejected: cannot find your hostname, [192.168.224.1]; from=<from-address> to=<to-address> proto=ESMTP helo=<mail-ej1-x631.google.com>

```

I am aware it has been posted here earlier that communication with gmail worked for some users (so it did for me, before this change, apparently).

is there any quick way to remedy this?
btw, I have not modified `main.cf`.

2022-10-14 16:40 UTC, GoliathLabs commented
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf Seems like you are behind a NAT? Because the 192.168.224.1 IP address comes from a private address space and is not the public facing IP of Google's infrastructure

2022-10-14 17:01 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf Seems like you are behind a NAT? Because the 192.168.224.1 IP address comes from a private address space and is not the public facing IP of Google's infrastructure

hey! thanks for a quick reply.

perhaps a "docker" kind of NAT? the mailserver is configured with proper public IPs, that's how I was able to receive email before, not sure I follow.
I am running a very simple compose setup.

I am aware the address comes from the private space, although there didn't appear to be any issues with it before. could I provide anything specific to help debug this?

btw I said to myself *yolo* and for the moment rolled back to the previous version (11.1.0), which immediately allowed me to receive mail from google again, even got some previously rejected messages finally delivered on retry.

2022-10-14 19:14 UTC, GoliathLabs commented
That is correct. With this version we check if there is a valid hostname behind the IP. Those checks weren't made in the previous release. Can you provide your mailserver env file and your docker compose file? (omit sensitive values)

2022-10-14 20:40 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> That is correct. With this version we check if there is a valid hostname behind the IP. In the previous release, these checks were not executed. Can you provide your mailserver env file and your docker compose file? (omit sensitive values)

sure:

`mailserver.env`:
```
ENABLE_SPAMASSASSIN=1
ENABLE_AMAVIS=0
# info loglevel
AMAVIS_LOGLEVEL=2

# SPAMASSASSIN_SPAM_TO_INBOX=1
SPAMASSASSIN_SPAM_TO_INBOX=0
# a third-party rule-set https://mcgrail.com/template/projects#KAM1, works properly since v11.0.0
ENABLE_SPAMASSASSIN_KAM=1
SA_SPAM_SUBJECT=""
# activate only if confident in bayes db for identifying spam/ham
# SA_SHORTCIRCUIT_BAYES_SPAM=1
# SA_SHORTCIRCUIT_BAYES_HAM=1

ENABLE_POSTGREY=0
# default is 300s
# POSTGREY_DELAY=120
# POSTGREY_DELAY=30
POSTGREY_DELAY=15

ENABLE_CLAMAV=0
ENABLE_FAIL2BAN=1
ENABLE_SASLAUTHD=0
ONE_DIR=1
# DMS_DEBUG=1 # replaced by LOG_LEVEL since v11.0.0
LOG_LEVEL=debug
SUPERVISOR_LOGLEVEL=info
SSL_TYPE=letsencrypt
TLS_TYPE=modern
DOVECOT_DEFAULT_PASS_SCHEME=ARGON2I
SPOOF_PROTECTION=0
ENABLE_SRS=0
ENABLE_MANAGESIEVE=1
ENABLE_UPDATE_CHECK=1
UPDATE_CHECK_INTERVAL=1d
# return 550 SMTP for rejects
# enabled 2022-09-15
POSTSCREEN_ACTION=enforce
# POSTSCREEN_ACTION=ignore
# daily postfix reports
PFLOGSUMM_TRIGGER=daily_cron
LOGWATCH_INTERVAL=weekly
```

compose file:
```
version: '3.8'

services:
  mailserver:
    # image: ghcr.io/docker-mailserver/docker-mailserver:latest
    # image: ghcr.io/docker-mailserver/docker-mailserver:10.4.0
    # image: ghcr.io/docker-mailserver/docker-mailserver:10.5.0
    # image: ghcr.io/docker-mailserver/docker-mailserver:11.0.0
    image: ghcr.io/docker-mailserver/docker-mailserver:11.1.0
	# 20220-10-14: issues with receiving from google, rolled back to 11.1.0.
    # image: ghcr.io/docker-mailserver/docker-mailserver:11.2.0
    mem_limit: 256m
    hostname: mail
    domainname: <domain name>
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    # More information about the mailserver ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    ports:
      - "25:25"      # SMTP  (explicit TLS => STARTTLS)
      # - "143:143"    # IMAP4 (explicit TLS => STARTTLS)
      - "587:587"    # ESMTP (explicit TLS => STARTTLS)
      - "465:465"    # ESMTP (implicit TLS)
      - "993:993"    # IMAP4 (implicit TLS)
      - "4190:4190"  # sieve
      # - "127.0.0.1:10001:10001"  # SRS
      # - "127.0.0.1:10002:10002"  # SRS
    volumes:
      - /var/lib/mailserver-docker/data/maildata:/var/mail
      - /var/lib/mailserver-docker/data/mailstate:/var/mail-state
      - /var/lib/mailserver-docker/data/maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - /etc/docker-mailserver/config/:/tmp/docker-mailserver/
      # necessary to copy the certs to their location when the below is used,
      # which is done by mailcrts.service regularly, triggered by
      # mailcrts.timer
      - /etc/docker-mailserver/letsencrypt/certs:/etc/letsencrypt/live/<maildomain>:ro
      - /etc/docker-mailserver/config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf

    restart: always
    stop_grace_period: 1m
    # cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    # sys_ptrace not needed as of 11.1.0
    cap_add: [ "NET_ADMIN", "SYS_PTRACE" ]
    env_file: /etc/docker-mailserver/mailserver.env
```

2022-10-14 21:54 UTC, casperklein commented
Does your host have IPv6 connectivity? That might explain the NAT: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/ipv6/

2022-10-15 13:14 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> Does your host have IPv6 connectivity? That might explain the NAT: https://docker-mailserver.github.io/docker-mailserver/edge/config/advanced/ipv6/

the host does indeed have IPv6 connectivity.

I will try to edit my compose file to have IPv6 work all the way through to the mailserver container, update again, test receiving from G and then report back (hopefully, all will be working then).

thanks for the pointer @casperklein

2022-10-15 13:31 UTC, GoliathLabs commented
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf can you post the log of the ipv6nat container on startup?

2022-10-15 13:33 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf can you post the log of the ipv6nat container on startup?

sure, it's restarting ("`restart: always`"), it's heaps of this:
```
Oct 15 15:31:44 host docker-compose[1083430]: mailserver-ipv6nat-1     | 2022/10/15 13:31:44 running [/sbin/iptables-t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `DOCKER':No such file or directory
Oct 15 15:31:44 host docker-compose[1083430]: mailserver-ipv6nat-1     |
Oct 15 15:31:44 host docker-compose[1083430]: mailserver-ipv6nat-1     | Try `iptables -h' or 'iptables --help' for more information.
Oct 15 15:31:44 host docker-compose[1083430]: mailserver-ipv6nat-1 exited with code 1
```

2022-10-15 15:00 UTC, GoliathLabs commented
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf 

Can you try this:

```
  ipv6nat:
    restart: always
    image: robbertkl/ipv6nat
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
    network_mode: "host"
 ```

2022-10-16 20:17 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> @wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf
> 
> Can you try this:
> 
> ```
>   ipv6nat:
>     restart: always
>     image: robbertkl/ipv6nat
>     privileged: true
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock:ro
>       - /lib/modules:/lib/modules:ro
>     network_mode: "host"
> ```

thanks, tried it just now. sadly, the result appears to be the same:
```
Oct 16 22:07:42 host docker-compose[1754468]: Container mailserver-mailserver-1  Created
Oct 16 22:07:42 host docker-compose[1754468]: Attaching to mailserver-ipv6nat-1, mailserver-mailserver-1
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     | Segmentation fault (core dumped)
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     | 2022/10/16 20:07:42 running [/sbin/iptables -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `DOCKER':No such file or directory
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     |
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     | Try `iptables -h' or 'iptables --help' for more information.
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1 exited with code 1
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     | 2022/10/16 20:07:42 running [/sbin/iptables -t nat -C OUTPUT -m addrtype --dst-type LOCAL -j DOCKER --wait]: exit status 2: iptables v1.8.7 (legacy): Couldn't load target `DOCKER':No such file or directory
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     |
Oct 16 22:07:42 host docker-compose[1754468]: mailserver-ipv6nat-1     | Try `iptables -h' or 'iptables --help' for more information.
Oct 16 22:07:43 host docker-compose[1754468]: mailserver-ipv6nat-1 exited with code 1
Oct 16 22:07:43 host docker-compose[1754468]: mailserver-ipv6nat-1 exited with code 1
Oct 16 22:07:44 host docker-compose[1754468]: mailserver-ipv6nat-1 exited with code 1
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-ipv6nat-1 exited with code 1
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-mailserver-1  | Restarted supervisord
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:45,343 INFO Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:45,343 INFO Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:45,343 INFO Set uid to user 0 succeeded
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:45,344 INFO RPC interface 'supervisor' initialized
Oct 16 22:07:45 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:45,345 INFO supervisord started with pid 2
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:46,348 INFO spawned: 'mailserver' with pid 25
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | [   INF   ]  Welcome to docker-mailserver 11.1.0
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | 2022-10-16 22:07:46,419 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | [   INF   ]  Initializing setup
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | [  DEBUG  ]  Registering functions
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | [   INF   ]  Checking configuration
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | [  DEBUG  ]  Checking that hostname/domainname is provided or overridden
Oct 16 22:07:46 host docker-compose[1754468]: mailserver-mailserver-1  | [  DEBUG  ]  Domain has been set to <domain redacted>
```

this is the setup without `mailserver` *depending* on the `ipv6nat`, otherwise you wouldn't see it starting up, but the result is still the same - `ipv6nat` refuses to work.
I said I was using `nftables` - it's actually the `iptables`-compatible version of `nftables` (I had troubles getting `docker` working with pure `nftables` setup, hence this), which makes this whole thing even weirder.

One last thing that came to mind is I am running the compose setup using `systemd` and in the unit file under the `[Service]` section I have set the following hardening options, which I can imagine, could hamper what `ipv6nat` is trying to do:
```systemd
CapabilityBoundingSet=
SystemCallFilter=~memfd_create
ProtectProc=invisible
ProtectHome=true
RestrictNamespaces=uts ipc pid user cgroup
NoNewPrivileges=True
#SecureBits=noroot-locked
PrivateTmp=true
DevicePolicy=closed
PrivateDevices=true
PrivateUsers=true
ProtectHostname=true
ProtectClock=true
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectKernelLogs=true
ProtectControlGroups=true
LockPersonality=true
MemoryDenyWriteExecute=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native
```

2022-10-20 13:49 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
would one of the solutions be disable ipv6 in postfix? I am willing to sacrifice ipv6 if that allows for a simpler way forward.
I assume that would require `sed -i`-ing `main.cf` with `user-patches.sh`.

2022-10-20 13:57 UTC, casperklein commented
No `sed` usage needed:

https://github.com/docker-mailserver/docker-mailserver/blob/b60b4015ab74d9a1b2cba47213919bfa8c2413fb/mailserver.env#L269-L283

2022-10-20 14:10 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> No `sed` usage needed:
> 
> https://github.com/docker-mailserver/docker-mailserver/blob/b60b4015ab74d9a1b2cba47213919bfa8c2413fb/mailserver.env#L269-L283

thanks, that's great.

one last question, though.
the domain that I am sending from/receiving at also works on its own and there exist both A and AAAA records for it. how will the mailservers of the world know how to contact me without being confused if postfix/dovecot will simply be refusing ipv6?
I feel it would be best if the mail domain was solely used for sending email and not anything else, but I wanted a `<address>@<domain>` instead of `<address>@mail.<domain>`...

2022-11-10 16:21 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> > Q: how will, e.g. Google's mailserver, know where to contact my mailserver without being confused when postfix/dovecot will simply be refusing ipv6?
> 
> I can imagine, that google will try IPv6 first and if connections cannot be established, it falls back to IPv4. But that's not guaranteed and up to google how they configured their mailserver.
> 
> You can use `address@domain`, but still point your MX record for that domain to `mail.domain`. That's no problem. If that were not possible, you would need one separate mailserver per domain. That would be crazy.
> 
> E.g. you can additional configure address@some-complete-different-domain, and point that domains MX record also to `mail.domain`.
> 
> And for `mail.domain` just create an A record, to process mail only via IPv4.

thanks @casperklein, that's what I end up doing in the end. also removed AAAA record for the mail domain and set postfix+dovecot to only work in ipv4 mode. it took a while for the new dmarc records to propagate but now it all works fine, I was even able to upgrade to the new version (11.2.0).
I am now running ipv4-only towards the future! :)

2022-11-13 14:48 UTC, GoliathLabs commented
@wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf keep in mind that IPv6 is becoming increasingly dominant across the web. It might be a good idea to look into supporting IPv6  (-only) servers in the future as well.

2022-11-13 19:22 UTC, wULLSnpAXbWZGYDYyhWTKKspEQoaYxXyhoisqHf commented
> It might be a good idea to look into supporting IPv6 (-only) servers in the future as well.

fair point, that's right, but until I find a way to run ipv6+nftables+docker that will most likely be a docker-less setup...
¯\_(ツ)_/¯

2023-01-04 16:08 UTC, casperklein commented
There might be issues regarding this PR: https://github.com/docker-mailserver/docker-mailserver/issues/2970

2023-01-04 17:59 UTC, GoliathLabs commented
@casperklein can't replicate the issue on my side

2023-01-04 18:01 UTC, casperklein commented
Same here, I am just wondering because there are at least two people with same/similar issues. IPv6 may be a factor.

2023-01-04 18:16 UTC, GoliathLabs commented
> Same here, I am just wondering because there are at least two people with same/similar issues. IPv6 may be a factor. My setup is IPv4 only.

But I think it depends on the network setup, as I also use IPv6, but in combination with an IPv6NAT container.