Integrated CI with Github Actions
docker-mailserver/docker-mailserver pull request #3
Opened 2021-01-04 18:55 UTC by radicand

This PR brings CI capabilities (lint, Docker build, test suite execution, Docker image publishing) to the project using native Github Actions.

Team: please note the source branch is a squash commit of the original gh-workflows branch we've been working off, in order to not pollute the commit history with all the testing commits involved with this effort.

2021-01-04 19:36 UTC, aendeavor commented
Very nice. We will now only need to adjust the Docker image in the files to use a proper Docker Hub account. How do we go about this? Or shall we even use the GitHub container registry as well?

I think the Docker Hub is a solution everyone knows. What#s the best way for some maintainers to open an account there. @erik-wramner do you know?

2021-01-04 21:09 UTC, fbartels requested changes
For some reason the test were not executed on this pr. Is the filter not matching?

2021-01-04 21:09 UTC, fbartels commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=afaerber0815/test-dm
Remnant user name?

2021-01-04 21:09 UTC, fbartels commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
Has there been a decision which platforms can reasonably be supported/maintained?

2021-01-04 21:09 UTC, fbartels commented on .github/workflows/build_test_push.yml
> +          NAME=afaerber0815/test-dm:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
The same leftover user? If the image is just built for testing it does not need a username attached

2021-01-04 21:11 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=afaerber0815/test-dm
> For some reason the test were not executed on this pr. Is the filter not matching?

I think that test are only run when they are on `master`. Since there are currently no tests registered in master, no tests are run.

2021-01-04 21:12 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
Fair question - not yet.

2021-01-04 21:12 UTC, fbartels commented
> What's the best way for some maintainers to open an account there

It's been a while, but I think the docker hub has a similar "organisation" feature. One needs to create an organisation and then could invite additional users for pushing images. When I last created an organisation it was free.

2021-01-04 21:12 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          NAME=afaerber0815/test-dm:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
See my comment above.

2021-01-04 21:13 UTC, aendeavor commented
> > What's the best way for some maintainers to open an account there
> 
> It's been a while, but I think the docker hub has a similar "organisation" feature. One needs to create an organisation and then could invite additional users for pushing images. When I last created an organisation it was free.

Could you do that again? I don't know how to do that.

2021-01-04 21:14 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=afaerber0815/test-dm
Yes, thanks for this catch. Once we have the docker details to use, we can update this to use the org/path. The process also needs us to add the secrets to Github for the docker username and docker password to use for pushing.

2021-01-04 21:16 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=afaerber0815/test-dm
> Yes, thanks for this catch. Once we have the docker details to use, we can update this to use the org/path. The process also needs us to add the secrets to Github for the docker username and docker password to use for pushing.

Exactly

2021-01-04 21:17 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          NAME=afaerber0815/test-dm:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
The build and test steps could potentially run from different executors, so we actually do need to push the image somewhere (so it can be later pulled). In this current iteration, we only push the sha-tagged version for use in tests, and then at the end of the chain it gets proper tagging if it passes. Regarding hardcoded user/path, same comment as above - this will need to be updated.

2021-01-04 21:40 UTC, fbartels commented
I have just registered the following organisation: https://hub.docker.com/orgs/mailserver

docker-mailserver got an error on being too long and just mailserver was miraculously still free. Add your docker usernames here so I can add you to it.

Regarding the test execution. The way I know it the tests are always executed with the state that they are in in the current branch. There may however be side effects since this is a fork. Not sure about that.

2021-01-04 21:52 UTC, aendeavor commented
> I have just registered the following organisation: https://hub.docker.com/orgs/mailserver
> 
> docker-mailserver got an error on being too long and just mailserver was miraculously still free. Add your docker usernames here so I can add you to it.

LOL This name was free? This is somehow blowing my mind right now. Nice job. My Docker username is: andevour

> Regarding the test execution. The way I know it the tests are always executed with the state that they are in in the current branch. There may however be side effects since this is a fork. Not sure about that.

I have no clue, but they work since they worked in the other repo as well. We will just need to adjust the names and secrets. @fbartels you should have access to the secrets section as a maintainer. If not, let me know and I will add you to the admins.

2021-01-04 21:53 UTC, fbartels commented
Ok, will look into this further tomorrow morning.

2021-01-05 07:34 UTC, fbartels commented
@aendeavor I have added you as an owner to the org. With the latest changes to the Docker pricing structure it seems that organisations there are now limited to three users. As the third user I would recommend to create dedicated user account for pushing images from CI.

Btw I checked the repo settings and were not able to find the section to add secrets for the Actions.

PS: what do you think about a private chat channel for users with admin and moderation access to this repo (with potentially opening it up for regular contributors)? That would give some more realtime interaction on cases like these. Something on Element/Matrix maybe?

2021-01-05 16:27 UTC, radicand commented on setup.sh
> +  if test -t 0
It would be good to know - I ended up doing this because `tty -s` is deprecated and `test -t 0` is the advised way to do it.

2021-01-05 16:34 UTC, erik-wramner commented on setup.sh
> +  if test -t 0
Please see commit 30c57b9. It changes `[ -t 1 ]` to `tty -s`. Unless you are very sure about this change I think we should stick to the tty command.

2021-01-05 16:51 UTC, radicand commented on setup.sh
> +  if test -t 0
From the manpage:
```
DESCRIPTION
     The tty utility writes the name of the terminal attached to standard input to standard output.  The name that is written is the string
     returned by ttyname(3).  If the standard input is not a terminal, the message ``not a tty'' is written.  The options are as follows:
     -s      Do not write the terminal name; only the exit status is affected when this option is specified.  The -s option is deprecated in favor of the ``test -t 0'' command.
```
I don't remember all the context behind the change, other than when I was debugging the test suite, I had issues with `tty -s` and it was one of the painful gotchas until identified. https://github.com/test-org-dm/docker-mailserver/commit/049fce281ad969907906483a16027465e3425e06 is where I changed it, in reference to tty -s not functioning in busybox (though I can't remember why busybox mattered (alpine related maybe)).

2021-01-05 17:09 UTC, aendeavor commented on setup.sh
> +  if test -t 0
When `tty -s` is deprecated, is there maybe another way of fixing this? If not, we should first try with the updated command since using deprecated commands should from my POV only be done if absolutely necessary.

2021-01-05 17:12 UTC, radicand commented on setup.sh
> +    USE_TTY="-t"
This is a hard requirement to work on Github actions, in case anyone wonders about this change.

2021-01-05 17:21 UTC, aendeavor commented on Makefile
> +NAME ?= tvial/docker-mailserver:testing
That's a good idea. Can you implement that? The registry is still `docker.io`, the repo is called `mailserver`.

The image has no name yet, but I guess `docker-mailserver` would be a good choice.

2021-01-05 18:38 UTC, aendeavor commented on Dockerfile
> -  sed -i -e 's/^module(load=\"imklog\")/#module(load=\"imklog\")/' /etc/rsyslog.conf && \
This was introduced with tomav/docker-mailserver#1711. Was the removal intended?

2021-01-05 18:39 UTC, aendeavor commented on Dockerfile
> -RUN chmod 0 /etc/cron.d/dovecot-purge.disabled
Is the removal of these lines intended? They were introduced with tomav/docker-mailserver#1705

2021-01-05 18:43 UTC, radicand commented on Dockerfile
> -RUN chmod 0 /etc/cron.d/dovecot-purge.disabled
No, this was a merge gone badly, I'm going to revert to an earlier commit and start again.

2021-01-05 18:48 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
But it seemed like it is okay to support the listed platforms, since the tests were fine in the test repository. If this is not the case, we can always remove a platform.

2021-01-05 18:48 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          NAME=afaerber0815/test-dm:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
This was corrected and is outdated. I'll mark it as resolved.

2021-01-05 18:49 UTC, aendeavor commented on Dockerfile
> +RUN c_rehash && echo "0 */6 * * * clamav /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam && \
I will tag @andreasfaerber here too, just to potentially speed up the answering process :)

2021-01-05 19:02 UTC, radicand commented on Dockerfile
> -  sed -i -e 's/^module(load=\"imklog\")/#module(load=\"imklog\")/' /etc/rsyslog.conf && \
This was due to a bad merge, it's now reverted out

2021-01-05 19:03 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=afaerber0815/test-dm
This has been updated now

2021-01-05 19:04 UTC, aendeavor commented on test/tests.bats
> +  assert_line --index 0 "Image: ${NAME}"
> NAME is set in the workflow file dynamically, but also has a default value set in Makefile. We could also add a default value in references in bats tests if needed (e.g., if test is initiated outside Makefile)

That's probably a good idea. Debugging this later could become painful and unnecessary

2021-01-05 19:06 UTC, radicand commented on setup.sh
> +    USE_TTY="-t"
Just did that now in ce1e440

2021-01-05 19:14 UTC, radicand commented on test/tests.bats
> +  assert_line --index 0 "Image: ${NAME}"
I just remembered we do set this in common.bash https://github.com/test-org-dm/docker-mailserver/blob/gha/ci/test/test_helper/common.bash#L7

2021-01-05 19:39 UTC, aendeavor commented on test/tests.bats
> +  assert_line --index 0 "Image: ${NAME}"
Alright. Then this is resolved:)

2021-01-06 07:48 UTC, fbartels commented on .github/workflows/build_test_push.yml
> +          NAME=${{ secrets.DOCKER_USERNAME }}/docker-mailserver-testing:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
This image could now simply be called "testing". The `docker_username` secret here would not work, as the name use the docker push user does not equal the name of the organisation.

2021-01-06 09:39 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/docker-mailserver-testing
It's the same here as below; we'll need to hard-code the repository name as the username of the bot does not match the repo name. I'm too for naming the testing image just `testing` instead of `docker-mailserver-testing`

2021-01-06 11:19 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/docker-mailserver-testing
I would have already done it, but for some reason, I cannot edit the files

2021-01-06 22:29 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          DOCKER_IMAGE=${{ secrets.DOCKER_USERNAME }}/docker-mailserver-testing
I've made these changes on both counts

2021-01-06 22:29 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          NAME=${{ secrets.DOCKER_USERNAME }}/docker-mailserver-testing:${GITHUB_SHA::8} bash -c 'make generate-accounts tests'
These changes are done now

2021-01-07 10:14 UTC, aendeavor commented
Alright. We are close to done. There are two steps left:

1. We will need to re-enable the whole `platforms` list for building more platforms. We will need to figure out which platforms we can comfortably support
2. We want to know the origin of the `c_rehash` command for Freshclam. If we do not receive an answer from @andreasfaerber, I'd suggest doing what @erik-wramner proposed, pushing the `c_rehash` a bit up

We ideally want to know about the `test -t 0` too, but I'd keep it as is for now.

2021-01-07 10:48 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
I'd propose to use

``` YAML
platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64
```

2021-01-07 15:54 UTC, aendeavor commented on setup.sh
> +  if test -t 0
We'll keep this in mind. But for now, I'd consider this okay and resolved.

2021-01-07 15:59 UTC, aendeavor commented on Dockerfile
> +RUN c_rehash && echo "0 */6 * * * clamav /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam && \
Apparently, it is needed. I had a look at the parent of https://github.com/test-org-dm/docker-mailserver/commit/a2c0c958e7bdd05adc9a45f4bb2f843e21ba6024 and the build failed. The `c_rehash` fixed this error. Since this is a CI/CD thing for GH Actions, we could possibly leave it where it is now.

The error in the parent commit is this: <https://github.com/test-org-dm/docker-mailserver/runs/1495103062#step:6:1891>

2021-01-07 17:51 UTC, casperklein commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
On the one hand, if an architecture builds, it should be good and no additional maintenance needed.

On the other hand, I think the platforms mentioned by @aendeavor  are the most commonly used. They cover 32/64 bit computer/server and Raspberry Pi/ARM devices. I've never come across hardware with ppc64le or s390x and don't think there is a demand for.

IMHO we should stick to the commonly used ones.

2021-01-07 18:12 UTC, casperklein commented
> A (private) chat channel is a good idea. As much as I like Element/Matrix, I think the best solution are GitHubs teams discussions. The GH organizations brings a few benefits, teams and team discussions are one of them. Matrix has the downside that we need yet another service on another website. I'd stick to GithHub in this case. I've opened a discussion on this [here](https://github.com/orgs/docker-mailserver/teams/administrators/discussions/1)

This is however limited to administrators I guess - I am getting a 404 error.

2021-01-07 18:19 UTC, aendeavor commented
> > A (private) chat channel is a good idea. As much as I like Element/Matrix, I think the best solution are GitHubs teams discussions. The GH organizations brings a few benefits, teams and team discussions are one of them. Matrix has the downside that we need yet another service on another website. I'd stick to GithHub in this case. I've opened a discussion on this [here](https://github.com/orgs/docker-mailserver/teams/administrators/discussions/1)
> 
> 
> 
> This is however limited to administrators I guess - I am getting a 404 error.

Indeed - I set it to be private, as the password for the bot account can be seen there. However, the maintainers and moderators team is public - so discussion s there are possible.

2021-01-07 18:37 UTC, casperklein commented
>  However, the maintainers and moderators team is public - so discussion s there are possible.

Ah ok, thank you. I didn't know that. I am pretty new to GH Teams..

2021-01-07 21:05 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
I would argue against the need for armv6 personally - it only exists in the original RPi, everything since RPi 2 has been ARM v7 or better. Similarly, 386 is not something I feel is worth supporting either - everything these days on Intel arch is 64-bit capable. As such, my vote goes for `platforms: linux/amd64,linux/arm/v7,linux/arm64`

2021-01-08 07:56 UTC, aendeavor commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
@radicand Alright, then pick these :) I think your line of argumentation is fine.

2021-01-08 12:07 UTC, erik-wramner commented on Dockerfile
> +RUN c_rehash && echo "0 */6 * * * clamav /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam && \
I'd rather move it one step up to the main install command unless it is related in some way to freshclam.

2021-01-08 12:18 UTC, aendeavor commented on Dockerfile
> +RUN c_rehash && echo "0 */6 * * * clamav /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam && \
Alright. Then we move it up:

``` BASH
  rm /etc/cron.daily/00logwatch && \
  c_rehash
```

2021-01-08 14:33 UTC, radicand commented on .github/workflows/build_test_push.yml
> +          platforms: linux/amd64,linux/arm64 # while developing to save time
Sounds good - just committed this.

2021-01-08 14:38 UTC, radicand commented
> For some reason the test were not executed on this pr. Is the filter not matching?

To follow up on this, it doesn't execute here because it's not part of this repo yet. Once the workflow is in the repo, it will execute according to the filters in it. It's a security feature to avoid leaking secrets and executing rogue actions directly from a pull request that someone has randomly done.

2021-01-08 14:58 UTC, aendeavor commented
@radicand You will not need to move the `c_rehash` because I'm currently refactoring the Dockerfile and I'm moving it up myself. (Please note @erik-wramner :D)

Therefore, this PR seems to be complete. We will need to review it again, then it can be merged.

2021-01-08 14:59 UTC, aendeavor commented on Dockerfile
> +RUN c_rehash && echo "0 */6 * * * clamav /usr/bin/freshclam --quiet" > /etc/cron.d/clamav-freshclam && \
See my comment: https://github.com/docker-mailserver/docker-mailserver/pull/3#issuecomment-756799020

This is resolved

2021-01-08 15:01 UTC, aendeavor approved these changes

2021-01-09 14:22 UTC, casperklein reviewed
fyi: I am new to GH actions. So all I can say about "build_test_push.yml" is: Looks good to me.

2021-01-12 08:47 UTC, aendeavor commented
@fbartels @erik-wramner do you think this PR is now okay to merge into the `transition` branch?

2021-01-12 08:57 UTC, fbartels approved these changes
Yes, looks good to me.

2021-01-12 11:09 UTC, aendeavor commented
@erik-wramner I'm going to merge this now since we have 3 out of 4 reviews and this PR is not the end since the `migration` branch will still need to be merged into `master`. Then I will require all reviews - I hope that's fine with you:)

2021-01-12 11:09 UTC, merged

2021-01-18 06:58 UTC, erik-wramner commented
It is of course fine, sorry I can't be more active @aendeavor. You're all doing a great job here.