docs: compress & improve user management docs
docker-mailserver/docker-mailserver pull request #3232
Opened 2023-04-08 11:45 UTC by georglauterbach

# Description

The user management docs are now one page, because the division between accounts and aliases is useless because there simply isn't enough content to justify the split. I improved and updated the text a bit.

## Type of change

- [x] This change is a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-04-08 12:15 UTC, georglauterbach commented
This PR can be merged at any time :)

2023-04-09 00:15 UTC, polarathene requested changes

2023-04-09 00:15 UTC, polarathene commented on docs/content/config/user-management.md
> +Users (email accounts) are managed in `/tmp/docker-mailserver/postfix-accounts.cf`. The best way to manage accounts is to use the reliable `setup` script inside the container. Just run `docker exec <
```suggestion
Users (email accounts) are managed in `/tmp/docker-mailserver/postfix-accounts.cf`. The best way to manage accounts is to use the reliable `setup` command inside the container. Just run `docker exec <CONTAINER NAME> setup help` and have a look at the section about subcommands, specifically the `email` subcommand.
```

2023-04-09 00:15 UTC, polarathene commented on docs/content/config/user-management.md
> +### Address Tags (Extension Delimiters) As an Alternative to Aliases
```suggestion
### Address Tags (Extension Delimiters) as an alternative to Aliases
```

2023-04-09 00:15 UTC, polarathene commented on docs/content/config/user-management.md
> +#### Via `setup` Inside the Container
```suggestion
#### Via `setup` inside the container
```

2023-04-09 00:15 UTC, polarathene commented on docs/content/config/user-management.md
> +### Adding a New Account
```suggestion
### Adding a new Account
```

2023-04-09 00:16 UTC, polarathene approved these changes

2023-04-09 09:27 UTC, merged