Image registry and setup update
docker-mailserver/docker-mailserver pull request #3233
Opened 2023-04-08 12:09 UTC by georglauterbach

# Description

Follow up to #3219.

Changes `docker.io/mailserver` for `ghcr.io/docker-mailserver`. Therefore updates `setup.sh` as well. So I figured it's okay to slightly adjust the docs for `setup.sh` as well.

## Type of change

- [x] Update (non-breaking change that does improve existing functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [x] If necessary I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2023-04-08 12:09 UTC, georglauterbach commented on docs/content/config/setup.sh.md
> -## Usage
I always thought this to be rather useless. I hope you agree :)

2023-04-09 01:24 UTC, polarathene requested changes

2023-04-09 01:24 UTC, polarathene commented on docs/content/config/setup.sh.md
> +[`setup.sh`][github-file-setupsh] is a script that aids in running commands inside your DMS container, including initial configuration. It has become a wrapper around `docker exec -ti <CONTAINER NAME
```suggestion
[`setup.sh`][github-file-setupsh] is a script that is complimentary to the internal `setup` command in `docker-mailserver`.

It mostly provides the convenience of aliasing `docker exec -ti <CONTAINER NAME> setup`, inferring the container name of a running `docker-mailserver` instance or running a new instance and bind mounting necessary volumes implicitly.
```

2023-04-09 01:24 UTC, polarathene commented on docs/content/config/setup.sh.md
> +By running `./setup.sh help`, usage information is printed.
```suggestion
For more information on using the script run: `./setup.sh help`.
```

2023-04-09 02:14 UTC, polarathene requested changes

2023-04-09 02:14 UTC, polarathene commented on target/bin/setup
> -    This is the main administration script that you use for all your interactions with
If you want to keep some of this description that was removed, you would want to relocate it to `setup.sh` in some manner, or the docs on `setup.sh`. I don't think it's relevant anymore to be interleaved into the main `setup` command help output.

---

I was not able to provide a web UI suggestion for changes and edited the file myself. The commit message detais:

- Remove dynamic support for showing command invoker via `${0}` for `./setup.sh` or `/usr/local/bin/setup`, just show `setup` command.
- Remove bulk of description text that isn't applicable to the `setup` command, but `./setup.sh` only.
- Revised description for help usage, as attempting `setup email help` or similar is not valid. Clarify to user they must be more specific.
- Revised the 2nd example description.
- Changed references of "script" to "CLI" which is now more accurate representation of the `setup` command.

2023-04-09 02:14 UTC, polarathene commented on target/bin/setup
> -    This is the main administration script that you use for all your interactions with
Note that most commands call scripts that will still output `./setup.sh` in their `help` output.

2023-04-09 02:14 UTC, polarathene commented on docs/content/config/setup.sh.md
> +    `setup.sh` is not required since v10.2.0. We encourage you to use `docker exec -ti <CONTAINER NAME> setup` instead.
If you want to keep this, that's fine.

I have made commits to your PRs which removed this admonition from other doc pages however. Changelog for v12 could probably express the information just as well.

---

This is clarified further down, so mostly redundant. If you'd like to keep it, maybe drop the version mention?

```suggestion
    `setup.sh` is not required. We encourage you to use `docker exec -ti <CONTAINER NAME> setup` instead.
```

2023-04-09 12:40 UTC, polarathene approved these changes

2023-04-09 19:39 UTC, wernerfred approved these changes

2023-04-09 21:55 UTC, casperklein approved these changes

2023-04-10 09:37 UTC, merged