docs: update docs that cite compose files
docker-mailserver/docker-mailserver pull request #3234
Opened 2023-04-08 12:20 UTC by georglauterbach

# Description

1. removed version marker (obsolete) and not used in our default Compose file
2. updated `domainname: mail` => `hostname: mail.*`

This PR may be merged at any time.

## Type of change

- [x] This change is a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2023-04-08 22:56 UTC, polarathene requested changes

2023-04-08 22:56 UTC, polarathene commented on docs/content/config/security/ssl.md
> +- `mail.example.com` will still uses `user@example.com` as the mail address.
```suggestion
- `mail.example.com` will still use `user@example.com` as the mail address. You do not need a bare domain for that.
```

2023-04-08 22:56 UTC, polarathene commented on docs/content/config/security/ssl.md
> +- We usually advise not to use a bare domain (_DNS MX record does not point to a subdomain_) for your `docker-mailserver`, but [just `example.com` is supported][docs-faq-baredomain].
```suggestion
- We usually discourage assigning a bare domain (_When your DNS MX record does not point to a subdomain_) to represent `docker-mailserver`. However, an FQDN of [just `example.com` is also supported][docs-faq-baredomain].
```

2023-04-08 23:24 UTC, polarathene approved these changes
LGTM :+1: 

I disabled auto-merge due to additional changes I made, you may want to briefly review them. Commits are either descriptive by title or provide a little bit more context in commit messages.

2023-04-09 09:38 UTC, georglauterbach commented
I like your suggestions 👍🏼

2023-04-09 09:42 UTC, merged