fix: Open-DKIM key generation broken
docker-mailserver/docker-mailserver pull request #3535
Opened 2023-09-12 17:33 UTC by luke-

With `ENABLE_OPENDKIM=1` and `ENABLE_RSPAMD=1` it's currently not possible to create DKIM Keys

# Description

Fixes #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2023-09-12 22:31 UTC, georglauterbach commented
Good observation! I'd actually like to error-out in a fail-fast way. This patch would hide a misconfiguration. I will add a suggestion.

2023-09-12 22:53 UTC, georglauterbach requested changes

2023-09-12 22:53 UTC, georglauterbach commented on target/bin/open-dkim
>  fi
```suggestion
if [[ -f /etc/dms-settings ]] && [[ $(_get_dms_env_value 'ENABLE_RSPAMD') -eq 1 ]]; then
  if [[ $(_get_dms_env_value 'ENABLE_OPENDKIM') -eq 1 ]]; then
    log 'error' "You enabled Rspamd and OpenDKIM - OpenDKIM will be implicitly used for DKIM keys"
  else
    /usr/local/bin/rspamd-dkim "${@}"
    exit
fi
```

2023-09-12 22:59 UTC, luke- commented
@georglauterbach Thanks, just merged your suggestion. 
Fyi: Not tested it. I'm not a bash scripting pro. Is there a `fi` missing?

2023-09-13 07:25 UTC, georglauterbach commented
> @georglauterbach Thanks, just merged your suggestion. 
> 
> Fyi: Not tested it. I'm not a bash scripting pro. Is there a `fi` missing?

There is 😂 Good observation!

2023-09-13 07:41 UTC, luke- commented
Ok, I've fixed and tested it.

2023-09-13 07:54 UTC, georglauterbach approved these changes

2023-09-13 08:42 UTC, merged