Add ENV `ENABLE_IMAP`
docker-mailserver/docker-mailserver pull request #3703
Opened 2023-12-17 00:08 UTC by casperklein

# Description

This PR adds the ENV `ENABLE_IMAP`. Like `ENABLE_POP3`, this allows to enable/disable IMAP.

In a POP3 only setup, this allows to not start the IMAP service.

Fixes #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] **I have added information about changes made in this PR to `CHANGELOG.md`**

2023-12-17 00:34 UTC, casperklein commented
This test failed: https://github.com/docker-mailserver/docker-mailserver/actions/runs/7235052163/job/19712079567

Re-running the test was successful.

2023-12-17 10:14 UTC, polarathene requested changes

2023-12-17 10:14 UTC, polarathene commented on CHANGELOG.md
> +  - ENV `SASL_PASSWD` ([#2946](https://github.com/docker-mailserver/docker-mailserver/pull/2946))
Placeholder?

2023-12-17 11:11 UTC, casperklein commented on CHANGELOG.md
> +  - ENV `SASL_PASSWD` ([#2946](https://github.com/docker-mailserver/docker-mailserver/pull/2946))
Oups, you are right.

2023-12-17 19:36 UTC, polarathene approved these changes

2023-12-18 09:27 UTC, georglauterbach commented
Are `ENABLE_POP3` and `ENABLE_IMAP` both zero or both one valid configurations?

2023-12-18 10:11 UTC, casperklein commented
Yes. Like most other ENVs, the values are only checked if equal 1 to enable it. All other values are considered to disable it. I haven't changed the logic, only streamlined the docs.

2023-12-18 10:47 UTC, georglauterbach approved these changes
👍🏼

2023-12-18 11:26 UTC, merged