tests: Revise `process_check_restart.bats`
docker-mailserver/docker-mailserver pull request #3780
Opened 2024-01-15 08:14 UTC by polarathene

# Description

**Revisions:**
- Removed some outdated comments about wrappers / timings that are no longer relevant.
- `pgrep` check now uses `--full` which was [initially required for MTA-STS support to pass the test](https://github.com/docker-mailserver/docker-mailserver/pull/3592#pullrequestreview-1814634068), whilst now it is more useful for matching postfix/amavis better.
- `pkill` now kills the process and asserts against the oldest matched process PID from `pgrep`. This should be the process that spawned any relevant children. Matching against the PID is better for targeting what we're interested in, since the process path is not always consistent (_`/usr/sbin/amavi` vs `/usr/sbin/amavisd-new`_).
- Added context for the python3 and postgrey services, along with additional maintainance comments on `pkill` / `pgrep` usage.

## Type of change

- [x] Improvement (non-breaking change that does improve existing functionality)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] New and existing unit tests pass locally with my changes
- [ ] **I have added information about changes made in this PR to `CHANGELOG.md`**

2024-01-15 09:51 UTC, georglauterbach requested changes
Just two smaller nitpicks; other than that LGTM 👍🏼

2024-01-15 09:51 UTC, georglauterbach commented on test/tests/parallel/set3/container_configuration/process_check_restart.bats
> +  local PID=$(docker exec "${CONTAINER_NAME}" pgrep --full --oldest "${PROCESS}")
```suggestion
  local PID=$(_exec_in_container pgrep --full --oldest "${PROCESS}")
```

2024-01-15 09:51 UTC, georglauterbach commented on test/tests/parallel/set3/container_configuration/process_check_restart.bats
> +  local IS_RUNNING=$(docker exec "${CONTAINER_NAME}" pgrep --full --list-full "${MIN_SECS_RUNNING[@]}" --oldest "${PROCESS}")
```suggestion
  local IS_RUNNING=$(_exec_in_container pgrep --full --list-full "${MIN_SECS_RUNNING[@]}" --oldest "${PROCESS}")
```

2024-01-15 21:32 UTC, polarathene commented
Weird test failure unrelated to changes in this PR 🤔 

```
not ok 71 [setup.sh] show usage when no arguments provided in 131ms
# (from function `assert_success' in file test/test_helper/bats-assert/src/assert_success.bash, line 42,
#  in test file test/tests/parallel/set3/scripts/setup_cli.bats, line 30)
#   `assert_success' failed
#
# -- command failed --
# status : 126
# output : ttrpc: closed: unknown
# --
#
```

https://github.com/docker-mailserver/docker-mailserver/blob/2bf52342500726e86362ee1ea5954b7d96533d32/test/tests/parallel/set3/scripts/setup_cli.bats#L28-L32

---

A quick search on `ttrpc: closed: unknown` shows it's related to running a container, but the results are fairly old. Perhaps something went awry on the CI instance 🤷‍♂️ I'll run it again after and it should pass.

2024-01-17 07:54 UTC, georglauterbach approved these changes

2024-01-17 09:46 UTC, merged