CHANGELOG.md: add breaking changes from rsyslog
docker-mailserver/docker-mailserver pull request #3854
Opened 2024-01-29 22:39 UTC by casperklein

# Description

Fixes https://github.com/docker-mailserver/docker-mailserver/pull/3403#issuecomment-1914742702

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] **I have added information about changes made in this PR to `CHANGELOG.md`**

2024-01-29 23:31 UTC, georglauterbach submitted a review, later dismissed

2024-01-29 23:32 UTC, polarathene requested changes
blocking - will provide feedback soon

2024-01-30 06:24 UTC, polarathene requested changes
Got a little bit more verbose than intended 😓 

I'll apply the two suggested changes, rest of the feedback is just heavy documentation for my benefit.

**EDIT:** Oh just realized the original notes were mostly paraphrased from the Debian changelog 😄

2024-01-30 06:35 UTC, polarathene submitted a review, later dismissed

2024-01-30 22:04 UTC, polarathene approved these changes

2024-01-30 22:04 UTC, merged