docs: misc improvements (but mostly related to Rspamd)
docker-mailserver/docker-mailserver pull request #3858
Opened 2024-01-30 16:32 UTC by georglauterbach

# Description

Various fixes to our Rspamd docs, CHANGELOG and PR template (wording).

Fixes #3857 but does even more

## Type of change

- [x] This change is a pure documentation update

2024-01-30 21:20 UTC, polarathene requested changes
LGTM 👍 

Some suggestions, mostly the ref link naming convention and DMS repo links (_use tag instead of master branch_)

---

> Many wording changes were pointed out by this tool; for someone on the looks for such a tool, I can highly recommend it :)

Quite cool, reminds me of Grammarly :)

2024-01-31 10:53 UTC, georglauterbach commented on docs/content/config/security/rspamd.md
> +```ini
VS Code does not render `env` correctly for me.

2024-01-31 10:54 UTC, georglauterbach commented
> LGTM 👍
> 
> Some suggestions, mostly the ref link naming convention and DMS repo links (_use tag instead of master branch_)

👍🏼 

> > Many wording changes were pointed out by this tool; for someone on the looks for such a tool, I can highly recommend it :)
> 
> Quite cool, reminds me of Grammarly :)

Yeah, but for less money and for more languages 🚀 It's funded by the EU directly as well, hence many languages in the EU are present.

2024-02-01 16:29 UTC, casperklein approved these changes

2024-02-01 23:00 UTC, polarathene commented on docs/content/config/security/rspamd.md
> +```ini
- Reason: https://markdown-all-in-one.github.io/docs/guide/syntax-highlighting-for-fenced-code-blocks.html#in-editor
- Supported languages: https://github.com/microsoft/vscode-markdown-tm-grammar/blob/main/build.js

Fixing that would require a PR to that `build.js` file, or an alternative described in the reason link.

`ini` is not semantically correct for what we're documenting. If it was just the syntax highlighting in the actual docs as an issue, that'd be an easy fix with an alias in `mkdocs.yml`.

---

Do we want to favor `ini` for VSCode to render the syntax? I had a look for ENV extensions on the marketplace that might have helped but came up empty.

2024-02-01 23:01 UTC, polarathene approved these changes

2024-02-02 12:49 UTC, casperklein commented on docs/content/config/security/rspamd.md
> +```ini
This seems to work quite well --> In VScode user `settings.json`:

```json
	"files.associations": {
		"*.env": "shellscript"
	},
```

2024-02-02 17:36 UTC, georglauterbach commented on docs/content/config/security/rspamd.md
> +```ini
Agreed, we'll stick to `env` then 👍🏼

2024-02-02 17:38 UTC, merged