fix: Apply SELinux security context after moving to mail-state
docker-mailserver/docker-mailserver pull request #3890
Opened 2024-02-14 15:02 UTC by robbertkl

# Description

After `setup.d/mail_state.sh` moves files/dirs from the container itself to `/var/mail-state`, they retains their SELinux security context labels, which are bound to the current container. When using named volumes, this leads to the files/dirs becoming inaccessible.

This PR lets the setup script apply the security context from the mail-state directory after moving, so they are still accessible when a new container is created that re-uses a named volume. The result is that the moved files will have the same security context as if they were created by the script.

This also explains the issue only occurs with the mail-state volume. In the other volumes only new files are created, instead of files being moved.

Fixes #3887 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary, I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] **I have added information about changes made in this PR to `CHANGELOG.md`**

2024-02-14 17:46 UTC, casperklein commented
LGTM 👍

Can this have any unwanted side-effects/problems on systems, not using SELinux security context?

2024-02-14 18:15 UTC, robbertkl commented
I've added ignoring the exit status (in case the scripts use `set -e`) and discarding stderr so there won't be any error message for non SELinux systems.

If the system supports SELinux but it's "Permissive" instead of "Enforcing", the `chcon` isn't really needed for it to work, although it prevents a lot of audit messages so is still nice to have. On a system without SELinux (I've tested on an old RancherOS host with linux 4.14) `chcon` fails and outputs an error; it doesn't do any harm (so shouldn't have any side effects), but I've now ignored the error so it doesn't pollute the container log.

2024-02-14 18:24 UTC, casperklein requested changes
Two changes to align with the style elsewhere used in DMS.

2024-02-14 18:24 UTC, casperklein commented on target/scripts/startup/setup.d/mail_state.sh
> +        chcon -R --reference="${STATEDIR}" "${DEST}" 2> /dev/null || true
```suggestion
        chcon -R --reference="${STATEDIR}" "${DEST}" 2>/dev/null || true
```

2024-02-14 18:24 UTC, casperklein commented on target/scripts/startup/setup.d/mail_state.sh
> +        chcon -R --reference="${STATEDIR}" "${DEST}" 2> /dev/null || true
```suggestion
        chcon -R --reference="${STATEDIR}" "${DEST}" 2>/dev/null || true
```

2024-02-14 19:22 UTC, robbertkl commented
Thanks, fixed!

2024-02-14 21:29 UTC, casperklein submitted a review, later dismissed

2024-02-15 11:04 UTC, robbertkl commented
@polarathene Just curious, did you assign me to update my branch? Just did and unassigned myself again, hope that's ok.

2024-02-15 11:09 UTC, georglauterbach commented
I re-assigned you; this makes finding PRs for maintainers easier.

2024-02-15 20:30 UTC, polarathene requested changes
I'll apply this.

2024-02-15 20:30 UTC, polarathene commented on CHANGELOG.md
> +- Ensure correct SELinux security context labels for files and directories moved to mail-state during setup ([#3890](https://github.com/docker-mailserver/docker-mailserver/pull/3890))
```suggestion
- Ensure correct SELinux security context labels for files and directories moved to the mail-state volume during setup ([#3890](https://github.com/docker-mailserver/docker-mailserver/pull/3890))
```

2024-02-15 20:32 UTC, polarathene approved these changes
LGTM! Like @casperklein I don't have the SELinux expertise to provide much feedback.

I'd merge but not sure if @georglauterbach wants to block for their own review.

2024-02-15 23:37 UTC, casperklein approved these changes

2024-02-16 06:34 UTC, georglauterbach commented
Go ahead and merge, not time to review this one :)

2024-02-16 07:24 UTC, merged