Dovecot fts solr tutorial
docker-mailserver/docker-mailserver pull request #4070
Opened 2024-06-16 10:25 UTC by beertje44

# Description

Tutorial on using standard apache solr container with dovecot provided solr schema as dovecot fts backend in dms.

Fixes #

https://github.com/docker-mailserver/docker-mailserver/pull/4025

## Type of change

- [x] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary, I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] **I have added information about changes made in this PR to `CHANGELOG.md`**

2024-06-16 10:47 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +version: "3.3"
`version` is deprecated.
```suggestion

```

2024-06-16 11:11 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +One of these is Apache SOLR, an fast and efficient multi-purpose search indexer.
Not 100% sure about this one:

```suggestion
One of these is Apache SOLR, a fast and efficient multi-purpose search indexer.
```

2024-06-16 11:11 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +
```suggestion
```

2024-06-16 11:11 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +We'll assume dms will connect internally to solr, so either append the above docker composer snippet to your dms compose.yml or make sure both containers use the same docker network.
```suggestion
We'll assume dms will connect internally to solr, so either append the above docker composer snippet to your dms `compose.yml` or make sure both containers use the same docker network.
```

2024-06-16 11:11 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +Create a 10-plugin.conf file in your config/dovecot folder and link it in your compose.yml like so:
```suggestion
Create a `10-plugin.conf` file in your `config/dovecot` folder and link it in your `compose.yml` like so:
```

2024-06-16 11:11 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +- solr-schema-9.xml
```suggestion
- `solr-config-9.xml`
- `solr-schema-9.xml`
```

2024-06-16 11:11 UTC, casperklein commented on docs/content/examples/tutorials/dovecot-solr.md
> +Copy solr-schema-9.xml to the data/dovecot folder and name it: schema.xml, remove managed-schema.xml
```suggestion
Copy `solr-config-9.xml` to the `data/dovecot` folder and name it: `solrconfig.xml`
Copy `solr-schema-9.xml` to the `data/dovecot` folder and name it: `schema.xml`, remove `managed-schema.xml`
```

2024-06-16 11:12 UTC, casperklein commented
```
fts      --> FTS
imap     --> IMAP
dms      --> DMS
dovecot  --> Dovecot
solr     --> Solr 
```

2024-06-16 16:43 UTC, georglauterbach requested changes
After @casperklein's and my feedback has been addressed, you will still need to adjust the `mkdocs.yml` to integrate your new page into our documentation.

The PR itself is still in a rough shape; I will also request @polarathene for a final review, as he has the most experience with our docs. I don't want him to have a third look currently, though; having the last word and final review is appropriate IMO.

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +*Dovecot full text search using solr backend*
```suggestion
# Dovecot Full Text Search (FTS) using the Solr Backend
```

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +```
Please add `yaml` after the 3 backticks so we get syntax highlighting.

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +```
Add a newline between these two and use the `bach` syntax highlighter (write `bash` after the three backticks).

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +https://github.com/dovecot/core/tree/main/doc
```suggestion
Stop the container, you should now have a data/dovecot folder. All that is needed on the solr part is a schema that is tailored specifically for dovecot fts. [Luckilly, Dovecot provides these](https://github.com/dovecot/core/tree/main/doc).
```

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +- solr-config-9.xml
```suggestion
As of writing of this guide solr 9 is current, so you need the 2 solr 9 config files:

- `solr-config-9.xml`
```

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +```
Add `yaml` after the backticks.

2024-06-16 16:43 UTC, georglauterbach commented on docs/content/examples/tutorials/dovecot-solr.md
> +```
Newline + `yaml` after backticks.

2024-06-16 18:13 UTC, georglauterbach commented
@polarathene go ahead and have a look :) I suggest you immediately apply feedback that you have 🚀 

---

@beertje44 you can now already take a look at the preview we generate. Look out for comments from the github-actions bot, [like this one](https://github.com/docker-mailserver/docker-mailserver/pull/4070#issuecomment-2171796039).

2024-06-18 02:38 UTC, polarathene commented
Current preview of new docs page: https://pullrequest-4070--dms-doc-previews.netlify.app/examples/tutorials/dovecot-solr/

I have revised the PR a bit:

- There was some parts from earlier review that had not been addressed (_notably naming convention from_ @casperklein and new line requirements from @georglauterbach ) , additionally some typos to correct.
- Other portions have been revised to be worded better, or restructured for better formatting for the reader to digest.
- Relevant links added for context. Especially the UID/GID reference.

---

There is no mention for the `dovecot-solr` package requirement. My understanding is that we are not bringing that back as it's missing support for ARM64 releases?

I'll add a new commit to advise on including the package and ARM64 caveat, then this should be good for merging.

2024-06-18 03:25 UTC, polarathene requested changes
I'll apply these.

2024-06-18 03:25 UTC, polarathene commented on docs/content/examples/tutorials/dovecot-solr.md
> +[docs::user-patches]: ../config/advanced/override-defaults/user-patches.md
```suggestion
[docs::user-patches]: ../../config/advanced/override-defaults/user-patches.md
[docs::dovecot::full-text-search]: ../../config/advanced/full-text-search.md
```

2024-06-18 03:25 UTC, polarathene commented on docs/mkdocs.yml
> +      - 'Full text search using Apache SOLR': examples/tutorials/dovecot-solr.md
```suggestion
      - 'Dovecot FTS with Apache Solr': examples/tutorials/dovecot-solr.md
```

2024-06-18 03:25 UTC, polarathene commented on docs/content/examples/tutorials/dovecot-solr.md
> +As the size of your mail storage grows, the benefits of FTS is especially notable:
```suggestion
Dovecot supports several FTS backends for providing fast and efficient full text searching of e-mails directly from the IMAP server.

As the size of your mail storage grows, the benefits of FTS are especially notable:
```

2024-06-18 03:25 UTC, polarathene commented on docs/content/examples/tutorials/dovecot-solr.md
> +
```suggestion

!!! warning "This is a community contributed guide"

    It extends [our official docs for Dovecot FTS][docs::dovecot::full-text-search] with a focus on Apache Solr. DMS does not officially support this integration.

```

2024-06-18 03:30 UTC, polarathene approved these changes

2024-06-18 03:40 UTC, polarathene commented
Thanks everyone!

This guide seems to be missing some advice that was detailed by @erm967 in https://github.com/docker-mailserver/docker-mailserver/issues/4052#issue-2338715252 , is that not required for some reason?

I suspect that is one of the maintenance caveats to keep in mind as the external resource won't be tied to a specific DMS release (_at least if this new doc page is not actively maintained across releases_).

---

I've left the referenced feature request open, but I've also included a link on the new docs page for any interested users to express their interest in the package. I think we've covered why we no longer include the package and the workaround for Solr users is quite simple as covered in the docs.

Closing that feature request with this PR is acceptable. It can always be opened again in future if relevant.

2024-06-18 06:46 UTC, georglauterbach approved these changes

2024-06-18 06:46 UTC, merged