Prevent Microsoft MUAs from sending reactions
docker-mailserver/docker-mailserver pull request #4120
Opened 2024-07-18 08:01 UTC by mpldr

# Description

Microsoft added a way to "react" to emails which is turned into
> [Image] <Name> liked this message.

No MUA except Microsoft's latest ones displays these properly and they are not providing significant value to an Email-exchange.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Improvement (non-breaking change that does improve existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (README.md or the documentation under `docs/`)
- [ ] If necessary, I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] **I have added information about changes made in this PR to `CHANGELOG.md`**

2024-07-19 08:04 UTC, polarathene requested changes

2024-07-19 08:04 UTC, polarathene commented on CHANGELOG.md
> +  - Disable Microsoft reactions to outgoing mail.
Please add a reference link to PR:

```suggestion
  - Disable Microsoft reactions to outgoing mail ([#4120](https://github.com/docker-mailserver/docker-mailserver/pull/4120))
```

2024-07-21 12:56 UTC, casperklein submitted a review, later dismissed
I am ambivalent about this PR. Personally I don't like that MS feature. But I am also not a fan of including app specific hacks into DMS.

For me, it would be fine to do such things via `user-patches.sh`.

2024-07-21 18:17 UTC, mpldr commented
> But I am also not a fan of including app specific hacks into DMS.

Me neither, but if a multi-billion dollar corporation feels like undermining standards, we – as in people invested in keeping the technology open and accessible – should make sure that this does not work with our systems. Google pulled something similar with XMPP and I would find it sad, if Microsoft did it to Email.

2024-07-21 22:03 UTC, polarathene approved these changes

2024-07-21 22:08 UTC, polarathene commented
We do not have the permission to rebase or merge master to update your branch, you'll need to update your branch again. Conflict would be from a recent PR that updated the `CHANGELOG.md`.

If the PR here doesn't cause any issues for users (_I don't know if it makes sense to expect the feature compatibility with DMS_), merging is fine. Otherwise I'd agree with @casperklein and just add a tip in our docs about it with `user-patches.sh`.

2024-07-22 11:41 UTC, polarathene approved these changes

2024-07-22 11:43 UTC, merged